import type { Vehicle, Testimonial, FAQ } from "@/types";

export const vehicles: Vehicle[] = [
  {
    id: "toyota-yaris",
    name: "Toyota Yaris",
    category: "economy",
    image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80",
    pricePerDay: 45,
    seats: 5,
    luggage: 2,
    transmission: "automatic",
    fuelType: "gasoline",
    ac: true,
    features: ["Bluetooth", "USB Port", "Backup Camera", "Air Conditioning"],
    available: true,
    description: "Perfect for solo travelers or couples exploring the island. Fuel-efficient and easy to park.",
  },
  {
    id: "honda-civic",
    name: "Honda Civic",
    category: "compact",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
    pricePerDay: 60,
    seats: 5,
    luggage: 3,
    transmission: "automatic",
    fuelType: "gasoline",
    ac: true,
    features: ["Bluetooth", "Apple CarPlay", "Backup Camera", "Cruise Control"],
    available: true,
    description: "Comfortable and reliable for longer drives across Jamaica. Ideal for small families.",
  },
  {
    id: "toyota-rav4",
    name: "Toyota RAV4",
    category: "suv",
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
    pricePerDay: 95,
    seats: 5,
    luggage: 4,
    transmission: "automatic",
    fuelType: "gasoline",
    ac: true,
    features: ["4WD", "Apple CarPlay", "Android Auto", "Sunroof", "Heated Seats"],
    available: true,
    description: "Tackle any terrain — from mountain roads to beach tracks. The go-to for adventure seekers.",
  },
  {
    id: "honda-crv",
    name: "Honda CR-V",
    category: "suv",
    image: "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80",
    pricePerDay: 90,
    seats: 5,
    luggage: 4,
    transmission: "automatic",
    fuelType: "gasoline",
    ac: true,
    features: ["AWD", "Backup Camera", "Apple CarPlay", "Blind Spot Monitoring"],
    available: true,
    description: "Spacious, smooth, and dependable. Great for families with extra luggage.",
  },
  {
    id: "toyota-hiace",
    name: "Toyota HiAce Van",
    category: "van",
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
    pricePerDay: 130,
    seats: 12,
    luggage: 8,
    transmission: "manual",
    fuelType: "diesel",
    ac: true,
    features: ["Large Cargo Space", "Air Conditioning", "USB Ports", "Tinted Windows"],
    available: true,
    description: "Perfect for large groups, wedding parties, or corporate teams. Comfortable seating for 12.",
  },
  {
    id: "mercedes-e-class",
    name: "Mercedes-Benz E-Class",
    category: "luxury",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    pricePerDay: 180,
    seats: 5,
    luggage: 3,
    transmission: "automatic",
    fuelType: "gasoline",
    ac: true,
    features: ["Premium Sound", "Leather Seats", "Panoramic Sunroof", "Driver Assistance", "Climate Control"],
    available: true,
    description: "Arrive in style. Our flagship luxury sedan for executives and special occasions.",
  },
  {
    id: "bmw-5-series",
    name: "BMW 5 Series",
    category: "luxury",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    pricePerDay: 200,
    seats: 5,
    luggage: 3,
    transmission: "automatic",
    fuelType: "gasoline",
    ac: true,
    features: ["M Sport Package", "Harman Kardon Audio", "Heated Seats", "Head-Up Display", "360 Camera"],
    available: true,
    description: "The ultimate driving machine. Precision engineering meets Jamaican paradise.",
  },
  {
    id: "toyota-hilux",
    name: "Toyota Hilux",
    category: "pickup",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    pricePerDay: 110,
    seats: 5,
    luggage: 6,
    transmission: "automatic",
    fuelType: "diesel",
    ac: true,
    features: ["4x4", "Tow Package", "Bed Liner", "Air Conditioning", "Bluetooth"],
    available: true,
    description: "Built for Jamaica's rugged terrain. Haul equipment, luggage, or gear with ease.",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Marcus Thompson",
    location: "New York, USA",
    rating: 5,
    text: "Ucal made our Jamaica vacation seamless. The RAV4 handled every road perfectly and the team was incredibly helpful. We'll be back!",
    date: "March 2026",
  },
  {
    id: "2",
    name: "Priya Sharma",
    location: "London, UK",
    rating: 5,
    text: "Booked the luxury charter for our wedding day. The Mercedes was immaculate and the driver was professional and punctual. Absolutely perfect service.",
    date: "February 2026",
  },
  {
    id: "3",
    name: "James & Claire O'Brien",
    location: "Toronto, Canada",
    rating: 5,
    text: "Best car rental experience we've had anywhere in the Caribbean. Transparent pricing, clean vehicles, and pickup was ready exactly on time.",
    date: "January 2026",
  },
  {
    id: "4",
    name: "Damion Williams",
    location: "Kingston, Jamaica",
    rating: 5,
    text: "I use Ucal for all my corporate travel needs. Their fleet is modern, the process is quick, and they always come through. Highly recommended.",
    date: "March 2026",
  },
  {
    id: "5",
    name: "Sarah Mitchell",
    location: "Miami, USA",
    rating: 5,
    text: "Rented the HiAce for a group trip. 10 of us, tons of luggage, and it was spacious and spotless. The team was warm and welcoming. Five stars.",
    date: "December 2025",
  },
];

export const faqs: FAQ[] = [
  {
    category: "Reservations",
    question: "How do I make a reservation?",
    answer: "You can book directly through our website in minutes. Select your pickup location, dates, and preferred vehicle, then complete the form with your details. You'll receive a confirmation email immediately.",
  },
  {
    category: "Reservations",
    question: "Can I modify or cancel my reservation?",
    answer: "Yes. You can modify or cancel your reservation up to 48 hours before pickup at no charge. Changes within 48 hours may be subject to a fee. Contact us directly for same-day modifications.",
  },
  {
    category: "Reservations",
    question: "What is the minimum rental period?",
    answer: "Our minimum rental is 24 hours. We offer daily, weekly, and monthly rates — with significant discounts for longer rentals.",
  },
  {
    category: "Requirements",
    question: "What documents do I need to rent a vehicle?",
    answer: "You'll need a valid driver's license (held for at least 2 years), a passport or national ID, and a valid credit or debit card. International visitors may drive with their home country license for up to 30 days.",
  },
  {
    category: "Requirements",
    question: "What is the minimum age to rent?",
    answer: "Renters must be at least 23 years old. Drivers aged 21–22 may rent select economy vehicles with a young driver surcharge.",
  },
  {
    category: "Payment",
    question: "What payment methods do you accept?",
    answer: "We accept all major credit and debit cards (Visa, Mastercard, American Express), as well as cash payments. A security deposit is required at pickup.",
  },
  {
    category: "Payment",
    question: "Is there a security deposit?",
    answer: "Yes. A refundable security deposit is held on your card at pickup. The amount varies by vehicle class — typically USD $200–$500. It is released within 5–7 business days after return if no damage or extra charges apply.",
  },
  {
    category: "Insurance",
    question: "Is insurance included in the rental price?",
    answer: "Basic third-party liability insurance is included in all rentals. We strongly recommend adding our Collision Damage Waiver (CDW) for full peace of mind. Full details are provided at booking.",
  },
  {
    category: "Pickup & Return",
    question: "Where can I pick up and return the vehicle?",
    answer: "We offer pickups and returns at Norman Manley International Airport (Kingston), Sangster International Airport (Montego Bay), and our main office in Kingston. Hotel delivery is available for an additional fee.",
  },
  {
    category: "Pickup & Return",
    question: "What happens if my flight is delayed?",
    answer: "We monitor all flight arrivals. If your flight is delayed, our team will wait for you at no extra cost — just let us know your flight number at booking.",
  },
  {
    category: "Charter Service",
    question: "What is included in the Luxury Charter Service?",
    answer: "Our charter includes a professional, uniformed driver, premium-class vehicles, complimentary water, and door-to-door service. We cater to airport transfers, weddings, corporate events, island tours, and private excursions.",
  },
  {
    category: "Charter Service",
    question: "Can I book the charter for a full-day tour?",
    answer: "Absolutely. Our full-day charter tours are popular for island exploration — covering spots like Dunn's River Falls, Port Antonio, the Blue Mountains, and more. Custom itineraries are welcome.",
  },
];

export const locations = [
  "Norman Manley International Airport (Kingston)",
  "Sangster International Airport (Montego Bay)",
  "Ucal Main Office — Kingston",
  "Hotel Delivery — Kingston Area",
  "Hotel Delivery — Montego Bay Area",
  "Ocho Rios (by request)",
  "Negril (by request)",
];
